services:
  postgres:
    image: postgres:16-alpine
    container_name: dot-mag-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    extra_hosts:
      - "hub.megan.ir:87.107.8.20"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      extra_hosts:
        - "hub.megan.ir:87.107.8.20"
    container_name: dot-mag-app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      INTERNAL_API_BASE_URL: ${INTERNAL_API_BASE_URL}
      ANDROID_SHA256_FINGERPRINT: ${ANDROID_SHA256_FINGERPRINT}
    ports:
      - "127.0.0.1:8090:3000"
    extra_hosts:
      - "hub.megan.ir:87.107.8.20"
    volumes:
      - web_uploads:/app/public/uploads
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  web_uploads:
    driver: local
